stages:
  - build
  - test
  - package

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  image: gradle:8.5-jdk21-alpine
  script:
    - gradle clean build -x test --build-cache --no-daemon
  artifacts:
    paths:
      - build/libs/*.jar
      - gradle/           # Include Gradle wrapper
      - gradlew
      - gradlew.bat
      - build.gradle.kts  # Include for dependency scanning
    expire_in: 1 hour

test:
  stage: test
  image: gradle:8.5-jdk21-alpine
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml
  services:
    - name: docker:27-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - gradle test --no-daemon

package:
  stage: package
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - apk add --no-cache openjdk21
  script:
    - ./gradlew bootBuildImage --imageName=registry.gitlab.com/kdg-ti/inf-curriculum/domain-integration/integration-5/2025-2026/team8/backend:${CI_COMMIT_SHORT_SHA}
    - docker tag registry.gitlab.com/kdg-ti/inf-curriculum/domain-integration/integration-5/2025-2026/team8/backend:${CI_COMMIT_SHORT_SHA} registry.gitlab.com/kdg-ti/inf-curriculum/domain-integration/integration-5/2025-2026/team8/backend:latest
    - docker push registry.gitlab.com/kdg-ti/inf-curriculum/domain-integration/integration-5/2025-2026/team8/backend:${CI_COMMIT_SHORT_SHA}
    - docker push registry.gitlab.com/kdg-ti/inf-curriculum/domain-integration/integration-5/2025-2026/team8/backend:latest
  only:
    - master
    - main
    - dev
    - qualitygate

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml


#gemnasium-gradle-dependency_scanning:
#  variables:
#    DS_JAVA_VERSION: 21


owasp_dependency_check:
  stage: test
  image: gradle:8.5-jdk21-alpine
  dependencies:
    - build
  script:
    - chmod +x gradlew
    - ./gradlew dependencyCheckAnalyze
  artifacts:
    paths:
      - build/reports/dependency-check-report.html
      - build/reports/dependency-check-report.json
    expire_in: 1 week
  allow_failure: true
  only:
    - master
    - main
    - dev